name: Release GitHub Page

# 起動のタイミング
on:
  push:
    branches:
      - master

# ジョブの定義
jobs:
  build:
    # 実行するインスタンス
    runs-on: ubuntu-latest
    environment: deploy
    # 各ステップの実行
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
#      - name: Set the value
#        run: |
#          echo "SEND_MAIL_ENDPOINT=${{ secrets.ENV }}" >> $GITHUB_ENV
      - run: yarn install
#      - run: yarn test
      - run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
